---
title: "HbdsDataScience Hotels"
author: "Francisco Javier Ortiz Escuchas"
date: "18 de marzo de 2019"
output: 
  word_document: null
  html_document: default
  number_sections: yes
  theme: cosmo
  highlight: default
---

******
## Carga de librerias
******
Load libraries (ggplot2,data.table,corrplot,lubridate,dplyr,doParallel,schoolmath)
```{r librerias, include=FALSE}
if(! "ggplot2" %in% installed.packages()) 
  install.packages("ggplot2",dependencies = TRUE)
library(ggplot2)
if(! "data.table" %in% installed.packages()) install.packages("data.table",dependencies = TRUE)
library(data.table)
if(! "corrplot" %in% installed.packages()) 
  install.packages("corrplot",dependencies = TRUE)
library(corrplot)
if(! "lubridate" %in% installed.packages()) 
  install.packages("lubridate",dependencies = TRUE)
library(lubridate)
if(! "dplyr" %in% installed.packages()) 
  install.packages("dplyr",dependencies = TRUE)
library(dplyr)
if(! "doParallel" %in% installed.packages()) 
  install.packages("doParallel",dependencies = TRUE)
library(doParallel)		# parallel processing
if(! "schoolmath" %in% installed.packages()) 
  install.packages("schoolmath",dependencies = TRUE)
library(schoolmath)		# parallel processing

#Limpiamos el espacio de trabajo
rm(list = ls());
gc();
```

******
## Carga de datos y análisis descriptivo de los datos
******
```{r descriptiva, echo=FALSE, message= FALSE}
# Cargamos los datos datasets macro, train y test
mainDir <- "/home/jortiz/tmp/hbdsdatascience/data"

if (dir.exists(mainDir)){
    setwd(file.path(mainDir))
} else {
    dir.create(file.path(mainDir))
    setwd(file.path(mainDir))
}

directorio_trabajo <- setwd(mainDir)
getwd()

# Con la libreria DoParallel vamos a emplear el proceso en paralelo para los 
# procesadores de mi máquina (Windows 10) que vamos a detectar automáticamente
cl <- makeCluster(detectCores())
registerDoParallel(cl)

# Cargamos el fichero con la función fread
hotels <- fread(file=paste(directorio_trabajo,"/Prueba_febrero.csv",sep = "", collapse = NULL), header=TRUE, sep=",", na.strings="NA", stringsAsFactors=TRUE)

# Limpiamos las variables del dataset hotels que vamos a emplear
#hotels[,Cost := as.double(hotels$Cost)][is.negative(Cost), Cost := hotels$Cost*(-1)]
#hotels$Cost[is.negative(hotels$Cost)] <- hotels$Cost*(-1)
#hotels$Invoice[is.decimal(hotels$Invoice)] <- as.integer(hotels$Invoice)
#hotels$Supplements[is.na(hotels$Supplements)] <- 0
#hotels$Country[(hotels$Country)] <- toupper(hotels$Country)
#hotels$BOOKING_WINDOW[is.na(hotels$BOOKING_WINDOW)] <- 0
#hotels[,timestamp := as.Date(CALDAY)]

#Resumen del dataset train
dim(hotels)

#Comentado para evitar que el informe sea muy extenso.
head(hotels)
tail(hotels)
summary(hotels)
str(hotels)
```

******
## Limpieza del dataset y selección de datos
******
```{r clean, echo=FALSE, message= FALSE}
# Cost per year
boxplot(hotels$Cost~year(hotels$CALDAY),data=hotels, main="Cost x year", xlab="year", ylab="Cost")

# Precios por sub-area
plot(hotels$Cost~hotels$Country, main="Cost x Country", xlab="Country", ylab="Cost", col="red")

# Número de transacciones por area
hotels %>%
    group_by(Category) %>%
    summarize(precio_medio = median(Cost)) %>%
    ggplot(aes(x = Category, y = precio_medio), size = 15) +
    geom_line(color = 'red') +
    geom_smooth(method = 'lm', color = 'grey', alpha = 0.7) + 
    ggtitle('Precio medio en el tiempo')

# Número de transacciones por area
hotels %>% 
    group_by(Country) %>%
    summarize(precio_medio = median(Cost)) %>%
    ggplot(aes(x = Country, y = precio_medio)) +
    #xlim(0,2000) +
    geom_bar(stat='identity') + 
    coord_flip() +
    labs(y='Numero de hotels', x='Country', title='Transantions per Country')

# Tipo producto x metro cuadrado
ggplot(hotels, aes(x = Cancelled, y = Region)) + geom_boxplot() + coord_flip()

# Precio medio por tiempo
hotels %>%
    group_by(fecha = year(CALDAY)) %>%
    summarize(precio_medio = median(Cost)) %>%
    ggplot(aes(x = fecha, y = precio_medio)) +
    geom_line(color = 'red') +
    geom_smooth(method = 'lm', color = 'grey', alpha = 0.7) + 
    ggtitle('Precio medio en el tiempo')

# Top 10 hoteles más interesantes/productivos
hotels %>%
    group_by(totHotels = ZHOTEL) %>%
    summarize(totCost = sum(Cost)) %>%
    ggplot(aes(x = totHotels, y = totCost), size = 10) +
    geom_line(color = 'red') +
    geom_smooth(method = 'lm', color = 'grey', alpha = 0.7) + 
    ggtitle('Top facturación 10 hoteles ')

    top10hotels <- hotels$ZHOTEL [order (hotels$Cost, decreasing = TRUE)]
    ggplot (data = subset (df, hotels$ZHOTEL %in% top10hotels [1 : 5]), 
            aes (Cost, ZHOTEL)) +
            geom_point (aes (color = factor (ZHOTEL)), size = 10)

```
******
## Prueba gráfico
******
```{r clean, echo=FALSE, message= FALSE}
    df2017 <- subset (hotels, year(CALDAY) == 2017)
    top10hotels <- df2017$ZHOTEL [order (df2017$Cost, decreasing = TRUE)]
    ggplot (data = subset (hotels, ZHOTEL %in% top10hotels [1 : 5]), 
            aes (Cost, ZHOTEL)) +
            geom_point (aes (color = factor (year(CALDAY) == 2017)), size = 10)
```

******
## Analisis variables correlación
******
Normalización de atributos
```{r exploratory,eval=TRUE, echo=FALSE}
# Matriz de correlación
train <- sapply(hotels,as.numeric)
matCor <- cor(subset(train,select = c(CALDAY,ZHOTEL,ID_Ref,Cost,Invoice,Region,Country,Category,Supplements,Cancelled,BOOKING_WINDOW)))

#Matriz de valores de train
corrplot(cor(matCor, use="pairwise.complete.obs"),method = "number",order ="alphabet")
```

#Paramos la paralelización
stopCluster(cl)
```
