---
title: "HbdsDataScience Invoices"
author: "Francisco Javier Ortiz Escuchas"
date: "18 de marzo de 2019"
output: 
  word_document: null
  html_document: default
  number_sections: yes
  theme: cosmo
  highlight: default
---

******
## Carga de librerias
******
Load libraries (tm,pdftools,magrittr,dplyr,doParallel)
```{r librerias, include=FALSE}
if(! "tm" %in% installed.packages()) 
  install.packages("tm",dependencies = TRUE)
library(tm)
if(! "pdftools" %in% installed.packages()) 
  install.packages("pdftools",dependencies = TRUE)
library(pdftools)
if(! "magrittr" %in% installed.packages()) 
  install.packages("magrittr",dependencies = TRUE)
library(magrittr)
if(! "dplyr" %in% installed.packages()) 
  install.packages("dplyr",dependencies = TRUE)
library(magrittr)
if(! "doParallel" %in% installed.packages()) 
  install.packages("doParallel",dependencies = TRUE)
library(doParallel)		# parallel processing

#Limpiamos el espacio de trabajo
rm(list = ls());
gc();
```

******
## Carga de datos
******
```{r descriptiva, echo=FALSE, message= FALSE}
# Cargamos los datos de los pdfs
mainDir <- "/home/jortiz/tmp/hbdsdatascience/data/Invoices"

# Con la libreria DoParallel vamos a emplear el proceso en paralelo para los 
# procesadores de mi máquina (Windows 10) que vamos a detectar automáticamente
cl <- makeCluster(detectCores())
registerDoParallel(cl)

# Cargamos los ficheros del directorio especifico
files <- list.files(path = mainDir,pattern = "pdf$" ,all.files=TRUE,
    full.names=TRUE)
```

******
## Lectura pdfs
******
```{r descriptiva, echo=FALSE, message= FALSE}

# Creamos la tabla
tableData <- data.frame("Client Ref." = c(),"importe" = c(), "Total" = c())
read <- readPDF(control = list(text = "-layout"))

# Recorremos todos los ficheros
for (i in 1:length(files)){
text <- strsplit(pdf_text(files[i]), "\n")
text[[1]]

#document <- Corpus(URISource(files[i]), readerControl = list(reader = read))
#doc <- content(document[[1]])

tableData <- rbind(tableData,data.frame("Client Ref." = substr(text[[1]][9],0,10) , "importe" =  substr(text[[1]][9],0,10), "Total" = substr(text[[1]][13],7,10)))
#document <- data.frame("Client Ref." = grep("Total\n", doc),  "importe" =  substr(doc,length(doc),10), "Total" = 0)
}

#colnames(document) <- c("Client Ref.", "Total Client", "Total")
#tableData <- rbind(tableData,document) 
```